---
title: "Carrera La Luz"
output: 
  flexdashboard::flex_dashboard:
    theme:
      bg: "#101010"
      fg: "#FDF7F7" 
      primary: "#ED79F9"
      base_font:
        google: Prompt
      code_font:
        google: JetBrains Mono
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
# Install thematic and un-comment for themed static plots (i.e., ggplot2)
# thematic::thematic_rmd()
library(ggplot2)
library(paqueteMET)

data("CarreraLuz22")

  
Theme2 = theme(
  axis.title.x = element_text(size = 8),
  axis.text.x = element_text(size = 8),
  axis.title.y = element_text(size = 8),
  # axis.text.y = element_blank(),
  axis.text = element_text( size = 8),
  legend.title = element_text(size = 8),
  legend.text = element_text(size = 8),  
  strip.text = element_text(size=8),
  title =element_text(size=8, face='bold')
)# tamaño letra por grupos

# subsets-----------------------------------------------------------------------
CarreraLuz22$sex[CarreraLuz22$sex == "M"]="Hombre"
CarreraLuz22$sex[CarreraLuz22$sex == "F"]="Mujer"
#-------------------------------------------------------------------------------
CarreraLuz22M = subset(CarreraLuz22, CarreraLuz22$sex=="Hombre")
CarreraLuz22F = subset(CarreraLuz22, CarreraLuz22$sex=="Mujer")

#-------------------------------------------------------------------------------
CarreraLuz22_c1M = subset(CarreraLuz22M, CarreraLuz22M$categoria=="1. Juvenil")
CarreraLuz22_c2M = subset(CarreraLuz22M, CarreraLuz22M$categoria=="2. Abierta")
CarreraLuz22_c3M = subset(CarreraLuz22M, CarreraLuz22M$categoria=="3. Veteranos A")
CarreraLuz22_c4M = subset(CarreraLuz22M, CarreraLuz22M$categoria=="4. Veteranos B")
CarreraLuz22_c5M = subset(CarreraLuz22M, CarreraLuz22M$categoria=="5. Veteranos C")


CarreraLuz22_c1F = subset(CarreraLuz22F, CarreraLuz22F$categoria=="1. Juvenil")
CarreraLuz22_c2F = subset(CarreraLuz22F, CarreraLuz22F$categoria=="2. Abierta")
CarreraLuz22_c3F = subset(CarreraLuz22F, CarreraLuz22F$categoria=="3. Veteranos A")
CarreraLuz22_c4F = subset(CarreraLuz22F, CarreraLuz22F$categoria=="4. Veteranos B")
CarreraLuz22_c5F = subset(CarreraLuz22F, CarreraLuz22F$categoria=="5. Veteranos C")
#-------------------------------------------------------------------------------

categoria= c("Juvenil","Abierta","Veteranos A", "Veteranos B","Veteranos C")
t2 = aggregate(CarreraLuz22$timerun/60, by=list(CarreraLuz22$categoria,CarreraLuz22$sex), FUN= summary)
t2=t2$x
t2m=t2[1:5,] 
row.names(t2m)=categoria
t2h=t2[6:10,] 
row.names(t2h)=categoria
```
Column { data-width=40 }
-----------------------------------------------------------------------
### volumen  {.value-box}
```{r}
valueBox(value = paste(length(CarreraLuz22$timerun),"atletas"), 
         caption = "Número de inscripciones", 
         icon = "fa-list-alt", 
         color = "#0EB0C6")
```

### distancia  {.value-box}
```{r}
valueBox(value = paste(10.07,"Km"), #ud1$min, 
         caption = "Distancia recorrida", 
         icon = "fa-refresh", 
         color = "#0EB0C6")
```


### promedio  {.value-box}
```{r}
valueBox(value = paste(round(mean(CarreraLuz22$timerun/60),2),"min"), 
         caption = "Tiempo promedio de carrera", 
         icon = "fa-clock", 
         color = "#0EB0C6")
```

### minimo  {.value-box}
```{r}
valueBox(value =paste(round(min(CarreraLuz22$timerun/60),1), "min"), 
         caption = "Tiempo ganador", 
         icon = "fa-star", 
         color = "#0EB0C6")
```


### velocidad  {.value-box}
```{r}
valueBox(value =paste(round(10070/min(CarreraLuz22$timerun),2),"m/s"), # ud1$cierre, 
         caption = "Máxima velocidad", 
         icon = "fa-chart-simple", 
         color = "#0EB0C6")
```

Column {data-width=800 .tabset}
-----------------------------------------------------------------------

### Analisis de Tiempos


```{r}
paleta6=c("#447270", "#6B9493", "#F6E271", "#F6B916", "#F69312", "#BC6C25")
p1=ggplot(CarreraLuz22F, aes(y=timerun/60, x=categoria))+
  geom_jitter(color="#034A94", size=1, alpha=0.9) +
  aes(color=paleta6)+
  labs(title = "Tiempos por categorias",
       y= "tiempo - min",
       x= "categorías")+ 
  #facet_wrap(~ sex)
  #facet_grid(vars(sex), scale="free")+
  ylim(0,170)+
  Theme2

p1
# Definición tamaño de letras

Theme1 = theme(axis.title.x = element_text(size = 16),   
axis.text.x = element_text(size = 10),
axis.title.y = element_text(size = 16),
# axis.text.y = element_blank(),
axis.text = element_text( size = 10),
legend.title = element_text(size = 10),
legend.text = element_text(size = 10),  
strip.text = element_text(size= 10),
title =element_text(size= 10, face='bold') )# tamaño letra por grupos

# Cálculo de los cuartiles
cuartiles1=data.frame(prob=c(0.25,0.5,0.75),
valor=quantile(CarreraLuz22_c2M$timerun,  c(0.25,0.5,0.75),na.rm = TRUE)/60 )
q=cuartiles1$valor

# Construcción de la gráfica

p4=ggplot(CarreraLuz22_c2M, aes(x=timerun/60, y=" ")) +
geom_jitter(color="#f95738", size=3, alpha=0.9)+ 
scale_color_manual(values="#034A94") +
geom_point(data=cuartiles1, aes(x=valor), color="#faf0ca",size=3)+
geom_boxplot(alpha = 0.4)+
labs(title = "distribución de tiempos", y= "",  x= "tiempo (min)")+ 
geom_text(size=6,data = NULL, x = q[1], y = 0.5, label = "Q1",col="#FF7F00")+
geom_text(size=6,data = NULL, x = q[2], y = 0.5, label = "Q2",col="#FF7F00") +
geom_text(size=6,data = NULL, x = q[3], y = 0.5, label = "Q3",col="#FF7F00") +
geom_text(size=6,data = NULL, x = 96, y = 0.5, label = "atípicos",col="#FF7F00") +  
Theme1
p4 

```

### Hombres

```{r, fig.height=3}
ggplot(CarreraLuz22M, aes(x = categoria, y = timerun/60 )) +
  geom_boxplot(aes(fill = categoria)) + 
  # facet_wrap(~sex, ncol=1, labeller = labeller(dose = etiquetas))+
  labs(title = "", y= "tiempo - min", x= "categorías")+
  scale_fill_brewer() +
  #scale_fill_manual(values = c("#00070D", "#012447", "#034A94", "#0570E1", "#3998FB","#37B6FC"))+
  theme(legend.position = "none")
t2h

```


### Mujeres
```{r, fig.height=3}
ggplot(CarreraLuz22F, aes(x = categoria, y = timerun/60 )) +
  geom_boxplot(aes(fill = categoria)) + 
  # facet_wrap(~sex, ncol=1, labeller = labeller(dose = etiquetas))+
  labs(title = "", y= "tiempo - min", x= "categorías")+
  scale_fill_brewer() +
  #scale_fill_manual(values = c("#00070D", "#012447", "#034A94", "#0570E1", "#3998FB","#37B6FC"))+
  theme(legend.position = "none")
t2m

```

Column {data-width=650 .tabset}
-----------------------------------------------------------------------
### Analisis comparativo de edades por sexo
```{r}
ggplot(CarreraLuz22, aes(y=edad , x=timerun/60 ))+
geom_point()+
facet_wrap(~ sex)

boxplot(CarreraLuz22$timerun/60~CarreraLuz22$sex,
main = "Distribución del tiempo carrera La Luz 2022",
ylab="tiempo (min)",
xlab = "sexo", las=1,
col=c("#f4d35e","#ee964b"))

```

### Categoria Juvenil

```{r, fig.height=3}
dataFc2=subset(CarreraLuz22, (CarreraLuz22$sex=="Mujer" & CarreraLuz22$categoria=="1. Juvenil")) # dataset de mujeres
x=dataFc2$timerun/60
stem(x) 

dataFc2=subset(CarreraLuz22, (CarreraLuz22$sex=="Hombre" & CarreraLuz22$categoria=="1. Juvenil")) # dataset de mujeres
x=dataFc2$timerun/60
stem(x) 

```

### Categoria Abierta

```{r, fig.height=3}
dataFc2=subset(CarreraLuz22, (CarreraLuz22$sex=="Mujer" & CarreraLuz22$categoria=="2. Abierta")) # dataset de mujeres
x=dataFc2$timerun/60
hist(x, xlim=c(30,120), ylim=c(0,100),las=1,
main = "MUJERES",
xlab="tiempo (min)",
ylab = "frecuencia",
col ="#ee964b")


dataMc2=subset(CarreraLuz22, (CarreraLuz22$sex=="Hombre" & CarreraLuz22$categoria=="2. Abierta")) # dataset de mujeres
x=dataMc2$timerun/60
hist(x, xlim=c(30,110), ylim=c(0,250),las=1,
main = "HOMBRES",
xlab="tiempo (min)",
ylab = "frecuencia",
col ="#ee964b")
 
```

### Categoria Veteranos A, B, C

```{r, fig.height=3}
library(plotrix)
proporciones <- c(276,147) # creamos un vector con proporciones
etiquetas <- c("Hombres","Mujeres") # vector con etiquetas
pie3D(proporciones,labels=etiquetas,
      explode=0.1,
      main="Diagrama de torta Veteranos A")

proporciones <- c(155,72) # creamos un vector con proporciones
etiquetas <- c("Hombres","Mujeres") # vector con etiquetas
pie3D(proporciones,labels=etiquetas,
      explode=0.1,
      main="Diagrama de torta Veteranos B")

proporciones <- c(58,16) # creamos un vector con proporciones
etiquetas <- c("Hombres","Mujeres") # vector con etiquetas
pie3D(proporciones,labels=etiquetas,
      explode=0.1,
      main="Diagrama de torta Veteranos C")

```





